[profile.default]
src = 'contracts'
out = 'out'
tests = 'test'
libs = ['lib']

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
